# Site settings
title: Jan Bednarik
header-img: img/home-bg.jpg
email: jan.bednarik@hotmail.cz
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://bednarikjan.github.io"
twitter_username: Jan Bednařík
github_username:  bednarikjan
facebook_username:  Jan Bednařík

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
