# Site settings
title: Jan Bednařík - projects and experience
email: jan.bednarik@hotmail.cz
description: "Projects I dived into"
logo_location: ""

baseurl: ""
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
